name: CI

on:
  pull_request:
    branches: [master]

jobs:
  kitchen-test:
    container:
      image: cincproject/workstation:latest
    runs-on: [self-hosted, linux]
    strategy:
      fail-fast: false
      matrix:
        platform: [centos-7, rhel-7]
        suite: [bake, full]
        cookbook: [aqha-example-web-app-cookbook-1, aqha-example-web-app-cookbook-2]
    env:
      KITCHEN_YAML: .kitchen.ec2.yml
      KITCHEN_TEST_SUBNET_ID: subnet-447b2523
    name: Kitchen Test
    steps:
      - uses: actions/checkout@v2
      - name: Run Kitchen test
        id: kitchen-test
        run: kitchen verify ${{ matrix.suite }}-${{ matrix.platform }}
        working-directory: cookbooks/${{ matrix.cookbook }}
      - name: KP
        id: kitchen-cleanup
        run: kitchen destroy ${{ matrix.suite }}-${{ matrix.platform }}
        working-directory: cookbooks/${{ matrix.cookbook }}
