name: CI

on:
  pull_request:
    branches: [master]

jobs:
  kitchen-test:
    container:
      image: cincproject/workstation:latest
    runs-on: [self-hosted, linux]
    strategy:
      fail-fast: false
      matrix:
        platform: [bake-centos-7, full-centos-7]
    env:
      KITCHEN_YAML: .kitchen.ec2.yml
      KITCHEN_TEST_SUBNET_ID: subnet-447b2523
    name: Kitchen Test
    steps:
      - uses: actions/checkout@v2
      - name: Run Kitchen test
        id: kitchen-test
        run: kitchen verify ${{ matrix.platform }}
      - name: KP
        id: kitchen-cleanup
        run: kitchen destroy ${{ matrix.platform }}
