name: CI

on:
  pull_request:
    branches: [master]

jobs:
  kitchen-tests:
    container:
      image: cincproject/workstation:latest
    runs-on: [self-hosted, linux]
    strategy:
      fail-fast: false
    env:
      KITCHEN_YAML: .kitchen.ec2.yml
      KITCHEN_TEST_SUBNET_ID: subnet-447b2523
    name: Kitchen Test
    steps:
      - uses: actions/checkout@v2
      - name: Run Kitchen test
        id: kitchen-test
        run: kitchen verify bake-centos-7
      - name: KP
        id: kitchen-cleanup
        run: kitchen destroy bake-centos-7
